trigger:
  branches:
    include:
      - main

variables:
  NODE_VERSION: '21.7.1'
  npm_config_cache: $(Pipeline.Workspace)/.npm
  selfHostedAgentPool: 'p4pa-dev-linux-app'

resources:
  repositories:
    - repository: pagopaCommons
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v18
      # Cannot use variables here!
      endpoint: 'azure-devops-github-ro'

pool:
  vmImage: 'ubuntu-22.04'

parameters:
  - name: env
    displayName: Target Environment
    type: string
    default: dev
    values:
      - dev
  - name: tag
    displayName: Target tests tag (use unquoted "all" to run every un-skipped test)
    type: string
    default: ''

stages:
  - stage: UX_tests
    dependsOn: [ ]
    pool:
      name: $(selfHostedAgentPool)
    jobs:
      - job: "Run_ux_tests_by_tag"
        condition: and(succeeded(), or(eq('${{ parameters.tag }}', ''), eq('${{ parameters.tag }}', 'all')))
        strategy:
          maxParallel: 3
          matrix:
            gestione enti:
              current_tag: 'ente'
            gestione tipi dovuti:
              current_tag: 'tipiDovuti'
            gestione dovuti:
              current_tag: 'dovuti'
            gestione flussi:
              current_tag: 'flussi'
        steps:
          - template: templates/node-job-setup/template.yaml@pagopaCommons
            parameters:
              nodeVersion: $(NODE_VERSION)
          - task: Cache@2
            inputs:
              key: 'npm | "$(Agent.OS)" | package.json'
              restoreKeys: |
                npm | "$(Agent.OS)"
              path: $(npm_config_cache)
            displayName: Cache npm
          - task: DownloadSecureFile@1
            name: pu_secrets
            displayName: 'Download PU secrets'
            inputs:
              secureFile: 'pu_ux_secrets.yaml'
          - script: |
              npm run tests --tags $TAGS --tags "~skip"
            displayName: 'Execute tests'
            env:
              PU_SECRET_PATH: $(pu_ux_secrets.secureFilePath)
              PU_TARGET_ENV: ${{ parameters.env }}
              TAGS: '$(current_tag)'
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: 'report/junitreport.xml'
              testRunTitle: 'Test Report'
              searchFolder: $(Build.SourcesDirectory)
            displayName: 'Publish Reports'
      - job: "Run_manual_ux_tests"
        condition: and(succeeded(), and( not(eq('${{ parameters.tag }}', '')), not(eq('${{ parameters.tag }}', 'all'))))
        steps:
          - template: templates/node-job-setup/template.yaml@pagopaCommons
            parameters:
              nodeVersion: $(NODE_VERSION)
          - task: Cache@2
            inputs:
              key: 'npm | "$(Agent.OS)" | package.json'
              restoreKeys: |
                npm | "$(Agent.OS)"
              path: $(npm_config_cache)
            displayName: Cache npm
          - task: DownloadSecureFile@1
            name: pu_secrets
            displayName: 'Download PU secrets'
            inputs:
              secureFile: 'pu_ux_secrets.yaml'
          - script: |
              npm run tests --tags "${{ parameters.tag }}" --tags "~skip"
            displayName: 'Execute tests'
            env:
              PU_SECRET_PATH: $(pu_ux_secrets.secureFilePath)
              PU_TARGET_ENV: ${{ parameters.env }}
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: 'report/junitreport.xml'
              testRunTitle: 'Test Report'
              searchFolder: $(Build.SourcesDirectory)
            displayName: 'Publish Reports'

