trigger:
  branches:
    include:
      - main

variables:
  nodeVersion: '21.7.1'
  npm_config_cache: $(Pipeline.Workspace)/.npm
  selfHostedAgentPool: 'p4pa-dev-linux-app'

pool:
  vmImage: 'ubuntu-22.04'

parameters:
  - name: env
    displayName: Target Environment
    type: string
    default: dev
    values:
      - dev
  - name: tag
    displayName: Target tests tag (use unquoted "all" to run every un-skipped test)
    type: string
    default: 'all'
    values:
      - all
      - enti
      - logo_ente
      - funzionalita_ente
      - pagamento
      - tipi_dovuto

stages:
  - stage: UX_tests
    dependsOn: [ ]
    pool:
      name: $(selfHostedAgentPool)
    jobs:
      - job: "Run_all_ux_tests"
        condition: and(succeeded(), or(eq('${{ parameters.tag }}', ''), eq('${{ parameters.tag }}', 'all')))
        strategy:
          maxParallel: 3
          matrix:
            gestione enti:
              current_tag: '@enti'
            gestione tipi dovuti:
              current_tag: '@tipi_dovuto'
            gestione dovuti:
              current_tag: '@dovuti'
            gestione flussi:
              current_tag: '@flussi'
        steps:
          - checkout: self
          - template: template\test-run.yml
            parameters:
              env: ${{ parameters.env }}
              tag: '$(current_tag)'
      - job: "Run_ux_tests_by_tag"
        condition: and(succeeded(), and( not(eq('${{ parameters.tag }}', '')), not(eq('${{ parameters.tag }}', 'all'))))
        steps:
          - checkout: self
          - template: template\test-run.yml
            parameters:
              env: ${{ parameters.env }}
              tag: ${{ parameters.tag }}