trigger:
  branches:
    include:
      - main
      
variables:
  NODE_VERSION: '22.2.0'
  npm_config_cache: $(Pipeline.Workspace)/.npm

pool:
  vmImage: 'ubuntu-22.04'

parameters:
  - name: env
    displayName: Target Environment
    type: string
    default: uat
    values:
      - dev
      - uat
  - name: tag
    displayName: Target tests tag (use unquoted "all" to run every un-skipped test)
    type: string
    default: 'all'
    values:
      - all
      - enti
      - tipi_dovuto
      - dovuti
      - pagamento
      - logo_ente
      - funzionalita_ente
      

stages:
  - stage: UX_tests
    dependsOn: [ ]
    jobs:
      - job: "${{ upper(parameters.env) }} Run all ux tests"
        condition: and(succeeded(), or(eq('${{ parameters.tag }}', ''), eq('${{ parameters.tag }}', 'all')))
        strategy:
          maxParallel: 2
          matrix:
            gestione enti:
              current_tag: 'enti'
            gestione tipi dovuti:
              current_tag: 'tipi_dovuto'
            gestione dovuti:
              current_tag: 'dovuti'
            gestione flussi:
              current_tag: 'flussi'
        steps:
          - checkout: self
          - template: template\test-run.yml
            parameters:
              env: ${{ parameters.env }}
              tag: '$(current_tag)'
      - job: "${{ upper(parameters.env) }} Run ux tests by tag"
        condition: and(succeeded(), and( not(eq('${{ parameters.tag }}', '')), not(eq('${{ parameters.tag }}', 'all'))))
        steps:
          - checkout: self
          - template: template\test-run.yml
            parameters:
              env: ${{ parameters.env }}
              tag: ${{ parameters.tag }}