userInfo:
  adminGlobal:
    userId: <ADMIN_GLOBAL_USER_ID>
    password: <ADMIN_GLOBAL_PWD>
    name: <ADMIN_GLOBAL_NAME>
    enteName: <ADMIN_GLOBAL_ENTE_NAME>
  adminEnte:
    userId: <ADMIN_ENTE_USER_ID>
    password: <ADMIN_ENTE_PWD>
    name: <ADMIN_ENTE_NAME>
    enteName: <ADMIN_ENTE_ENTE_NAME>
  operator:
    userId: <OPERATOR_USER_ID>
    password: <OPERATOR_PWD>
    name: <OPERATOR_NAME>
    enteName: <OPERATOR_ENTE_NAME>
ente:
  fiscal_code:
    X: <FISCAL_CODE_ENTE_X>
    Y: <FISCAL_CODE_ENTE_Y>
    Z: <FISCAL_CODE_ENTE_Z>
    notValid: <FISCAL_CODE_ENTE_NOT_VALID>
    A: <FISCAL_CODE_ENTE_A>
