<ENV>:
  pageUrl: <PAGE_URL>
  userInfo:
    adminGlobal:
      userId: <ADMIN_GLOBAL_USER_ID>
      password: <ADMIN_GLOBAL_PWD>
      name: <ADMIN_GLOBAL_NAME>
      enteName: <ADMIN_GLOBAL_ENTE_NAME>
      codFedUserId: <ADMIN_GLOBAL_COD_FED_USER_ID>
    adminEnte:
      userId: <ADMIN_ENTE_USER_ID>
      password: <ADMIN_ENTE_PWD>
      name: <ADMIN_ENTE_NAME>
      enteName: <ADMIN_ENTE_ENTE_NAME>
      codFedUserId: <ADMIN_ENTE_COD_FED_USER_ID>
    operator:
      userId: <OPERATOR_USER_ID>
      password: <OPERATOR_PWD>
      name: <OPERATOR_NAME>
      enteName: <OPERATOR_ENTE_NAME>
      codFedUserId: <OPERATOR_COD_FED_USER_ID>
  ente:
    intermediato1:
      fiscalCode: <FISCAL_CODE_INTERMEDIATO_1>
      name: <ENTE_NAME_INTERMEDIATO_1>
      codTassonomicoTipoDovuto: <COD_TASS_TIPO_DOVUTO_INTERMEDIATO_1>
      iban: <IBAN_INTERMEDIATO_1>
    intermediato2:
      fiscalCode: <FISCAL_CODE_INTERMEDIATO_2>
      iban: <IBAN_INTERMEDIATO_2>
      codTassonomicoTipoDovuto: <COD_TASS_TIPO_DOVUTO_INTERMEDIATO_2>
      iban: <IBAN_INTERMEDIATO_2>
    fiscal_code:
      notValid: <FISCAL_CODE_ENTE_NOT_VALID>
      A: <FISCAL_CODE_ENTE_A>
      B: <FISCAL_CODE_ENTE_B>
      T: <FISCAL_CODE_ENTE_T>
  citizenInfo: 
    maria:
      name: <CITIZEN_NAME>
      fiscalCode: <CITIZEN_FISCAL_CODE>
      email: <CITITZEN_EMAIL>
      card:
        number: <CARD_NUMBER>
        expirationDate: <CARD_EXPIRATION_DATE>
        securityCode: <CARD_SECURITY_CODE>
  checkout:
    pageUrl: <CHECKOUT_URL>
    email: <EMAIL_FOR_CHECKOUT>
    paymentMethod: <PAYMENT_METHOD_CHECKOUT>
