<ENV>:
  pageUrl: <PAGE_URL>
  userInfo:
    password: <PASSWORD_LOGIN>
    adminIntermediato2:
      username: <INTERMEDIATO_2_USERNAME>
    adminEnteLocale:
      username: <ENTE_LOCALE_USERNAME>
  citizenInfo: 
    name: <CITIZEN_NAME>
    fiscalCode: <CITIZEN_FISCAL_CODE>
    card:
      number: <CARD_NUMBER>
      expirationDate: <CARD_EXPIRATION_DATE>
      securityCode: <CARD_SECURITY_CODE>
  checkout:
    pageUrl: <CHECKOUT_URL>
    email: <EMAIL_FOR_CHECKOUT>
    paymentMethod: <PAYMENT_METHOD_CHECKOUT>
