userInfo:
  adminGlobal:
    userId: <ADMIN_GLOBAL_USER_ID>
    password: <ADMIN_GLOBAL_PWD>
    name: <ADMIN_GLOBAL_NAME>
  adminEnte:
    userId: <ADMIN_ENTE_USER_ID>
    password: <ADMIN_ENTE_PWD>
    name: <ADMIN_ENTE_NAME>
  operator:
    userId: <OPERATOR_USER_ID>
    password: <OPERATOR_PWD>
    name: <OPERATOR_NAME>
