userInfo:
  adminGlobal:
    userId: 'DMEMPY15L21L736U'
    password: 'thePassword'
    name: 'demo demo'
  adminEnte:
    userId: 'testAdminEnte'
    password: 'thePassword'
    name: 'Mario Bianchi'
  operator:
    userId: 'testOperatore'
    password: 'thePassword'
    name: 'Mario Rossi'
